# Generated by Django 5.2.4 on 2025-08-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('shopkeeper', 'Shopkeeper')], default='customer', max_length=20),
        ),
    ]
