# Generated by Django 5.2.4 on 2025-08-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
