# Generated by Django 5.2.4 on 2025-08-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
